import React from 'react';
import Carousel from 'react-bootstrap/Carousel'

import "./controls.css";

function Slideshow() {
    return (
        <Carousel>
            <Carousel.Item>
                <img
                    className="diamondback"
                    src="https://i.imgur.com/xH27TgK.jpg"
                    alt="logo"
                />
            </Carousel.Item>
            <Carousel.Item>
                <img
                    className="bansheeLogo"
                    src="https://i.imgur.com/UTHbCky.jpg"
                    alt="logo"
                />
            </Carousel.Item>
            <Carousel.Item>
                <img
                    className="banshee"
                    src="https://i.imgur.com/t83bDRw.jpg?1"
                    alt="logo"
                />
            </Carousel.Item>
            <Carousel.Item>
                <img
                    className="orion"
                    src="https://i.imgur.com/5s2cZLg.jpg"
                    alt="logo"
                />
            </Carousel.Item>
            <Carousel.Item>
                <img
                    className="copperheadStrikeLogo"
                    src="https://i.imgur.com/ZpGHGam.jpg"
                    alt="logo"
                />
            </Carousel.Item>
            <Carousel.Item>
                <img
                    className="furyLift"
                    src="https://i.imgur.com/Z4cANXR.jpg"
                    alt="logo"
                />
            </Carousel.Item>
            <Carousel.Item>
                <img
                    className="furyLogo"
                    src="https://i.imgur.com/fXaPJGw.jpg"
                    alt="logo"
                />
            </Carousel.Item>
            <Carousel.Item>
                <img
                    className="gatekeeperLogo"
                    src="https://i.imgur.com/Clyvuzj.jpg"
                    alt="logo"
                />
            </Carousel.Item>
            <Carousel.Item>
                <img
                    className="millenniumforce"
                    src="https://i.imgur.com/LWgpdue.jpg"
                    alt="logo"
                />
            </Carousel.Item>
            <Carousel.Item>
                <img
                    className="nighthawkLoop"
                    src="https://i.imgur.com/gIz7nXn.jpg"
                    alt="logo"
                />
            </Carousel.Item>
            <Carousel.Item>
                <img
                    className="raptor"
                    src="https://i.imgur.com/ykGUdHo.jpg"
                    alt="logo"
                />
            </Carousel.Item>
            <Carousel.Item>
                <img
                    className="steelVengeance"
                    src="https://i.imgur.com/HRZzCG6.jpg"
                    alt="logo"
                />
            </Carousel.Item>
            <Carousel.Item>
                <img
                    className="steelVengeanceLogo"
                    src="https://i.imgur.com/vqVdpoR.jpg"
                    alt="logo"
                />
            </Carousel.Item>
            <Carousel.Item>
                <img
                    className="valravnLogo"
                    src="https://i.imgur.com/ja0eOS8.jpg"
                    alt="logo"
                />
            </Carousel.Item>
            <Carousel.Item>
                <img
                    className="wickedtwister"
                    src="https://i.imgur.com/K149SVe.jpg"
                    alt="logo"
                />
            </Carousel.Item>
            <Carousel.Item>
                <img
                    className="ironDragonTrains"
                    src="https://i.imgur.com/atBbZG5.jpg"
                    alt="logo"
                />
            </Carousel.Item>
        </Carousel>
    );
}


export default Slideshow;