import React from 'react';
import Carousel from 'react-bootstrap/Carousel'

import "./controls.css";

function Slideshow() {
    return (
        <Carousel>
            <Carousel.Item>
                <img
                    className="diamondback"
                    src="./Diamondback.JPG"
                    alt="logo"
                />
            </Carousel.Item>
            <Carousel.Item>
                <img
                    className="banshee"
                    src="./Banshee.JPG"
                    alt="logo"
                />
            </Carousel.Item>
            <Carousel.Item>
                <img
                    className="orion"
                    src="./Orion.JPG"
                    alt="logo"
                />
            </Carousel.Item>
            <Carousel.Item>
                <img
                    className="copperheadStrikeLogo"
                    src="./copperheadLogo.JPG"
                    alt="logo"
                />
            </Carousel.Item>
            <Carousel.Item>
                <img
                    className="furyLift"
                    src="./furyLift.JPG"
                    alt="logo"
                />
            </Carousel.Item>
            <Carousel.Item>
                <img
                    className="furyLogo"
                    src="./furyLogo.JPG"
                    alt="logo"
                />
            </Carousel.Item>
            <Carousel.Item>
                <img
                    className="gatekeeperLogo"
                    src="./gatekeeperLogo.JPG"
                    alt="logo"
                />
            </Carousel.Item>
            <Carousel.Item>
                <img
                    className="millenniumforce"
                    src="./millenniumForce.JPG"
                    alt="logo"
                />
            </Carousel.Item>
            <Carousel.Item>
                <img
                    className="nighthawkLoop"
                    src="./nighthawkLoop.JPG"
                    alt="logo"
                />
            </Carousel.Item>
            <Carousel.Item>
                <img
                    className="raptor"
                    src="./raptor.JPG"
                    alt="logo"
                />
            </Carousel.Item>
            <Carousel.Item>
                <img
                    className="steelVengeance"
                    src="./steelVengeance.JPG"
                    alt="logo"
                />
            </Carousel.Item>
            <Carousel.Item>
                <img
                    className="steelVengeanceLogo"
                    src="./steelVengeanceLogo.JPG"
                    alt="logo"
                />
            </Carousel.Item>
            <Carousel.Item>
                <img
                    className="valravnLogo"
                    src="./valravnLogo.JPG"
                    alt="logo"
                />
            </Carousel.Item>
            <Carousel.Item>
                <img
                    className="wickedtwister"
                    src="./wickedtwister.JPG"
                    alt="logo"
                />
            </Carousel.Item>
        </Carousel>
    );
}


export default Slideshow;